### ISSUE TITLE
403 Error (original title) - No menu options showing up

### ISSUE THREAD

**Issue by Electromaster232** [yariplus/nodebb-plugin-minecraft-integration#107]
Plugin reports there is an issue with my firewall, but I have already checked and it should be working, what port does it try to use cause my NGINX config is a little wonky at the minute?

**Comment by yariplus** [comment]
It uses the same port as the website address listed in game, when you do `/nodebb url`

You can also set a different address for socket.io to use by doing `/nodebb live [address]`

Using `/nodebb debug toggle` may also provide additional details in the log.

**Comment by Electromaster232** [comment]
![screen shot 2017-09-30 at 2 31 49 pm](https://user-images.githubusercontent.com/25728719/31048506-4a0921f6-a5ec-11e7-9056-21b0cbce68ed.png)


NodeBB URL just returns my website address (no port), maybe thats the issue? tried nodebb live, same error, you can see from the screenshot what the verbose logging provides. @yariplus

**Comment by yariplus** [comment]
Thanks. Are you using cloudflare at all? SSL?

The address should be the same you use to access the forum on a browser, so if you don't need a port on a browser, you don't need it here either.

**Comment by Electromaster232** [comment]
@yariplus yes, both

**Comment by yariplus** [comment]
Check if your Minecraft server's real IP address is whitelisted under your cloudflare Firewall settings.

![https://puu.sh/xMLdA/d9a45028c5.png](https://puu.sh/xMLdA/d9a45028c5.png)

**Comment by Electromaster232** [comment]
Getting this error:
![screen shot 2017-09-30 at 2 31 49 pm](https://user-images.githubusercontent.com/25728719/31049276-161f8490-a5fe-11e7-86bc-556a63def0f4.png)

**Comment by Electromaster232** [comment]
![screen shot 2017-09-30 at 4 39 03 pm](https://user-images.githubusercontent.com/25728719/31049282-2d0bb714-a5fe-11e7-8bc1-ec8be652ac02.png)

Added IP to cloudflare and got this
@yariplus

**Comment by yariplus** [comment]
Hmm, something still blocking the connection. See if turning CF to a grey cloud changes the error.

Also, make sure `/nodebb url` and `/nodebb live` are set to the same address.

**Comment by Electromaster232** [comment]
tried, same error @yariplus

**Comment by phit** [comment]
make sure the URL matches the URL in the config.json of NodeBB, if it doesn't you will have add acccepted urls in the config to whatever the plugin will use

https://github.com/NodeBB/NodeBB/issues/5472#issue-209820291

**Comment by Electromaster232** [comment]
@phit it does and dosen't it does in the sense that the URL is the same, but in the config I have a port specified (4567) that NGINX proxies for me. Would that be affecting it?

**Comment by Electromaster232** [comment]
Addendum: Emails and such do link to this port (4567) which is blocked by firewall cause its not needed, that has to be the issue, but idk how to fix it.

**Comment by phit** [comment]
change the URL in the config to the actual URL you access the forum from, that will also fix the link in emails etc.

the port shouldnt be in that URL!

**Comment by Electromaster232** [comment]
Did, still the same error. Let me restart the MC server instead of just reloading the plugin.

**Comment by yariplus** [comment]
Thanks for helping Phit. Just fyi, the plugin runs on a different thread, so `/nodebb reload` and restarting the server should have the same effect. Sounds like you're on the right track with the ports being the issue.

**Comment by Electromaster232** [comment]
I don't get it lol, there should be NOTHING in the way of port 443 or whatever SSL runs on. 😢 
@yariplus @phit

**Comment by phit** [comment]
@yariplus https://github.com/yariplus/nodebb-plugin-minecraft-integration/issues/103#issuecomment-298251596

derp, was this actually ever fixed in the plugin? I'm still running with accept `*:*`

**Comment by Electromaster232** [comment]
@phit let me give that a shot one minute

**Comment by Electromaster232** [comment]
![screen shot 2017-09-30 at 9 28 21 pm](https://user-images.githubusercontent.com/25728719/31050872-58b9089e-a626-11e7-85a6-aa261974cee0.png)
![screen shot 2017-09-30 at 9 27 05 pm](https://user-images.githubusercontent.com/25728719/31050873-5991a51e-a626-11e7-8128-dd92123175c9.png)

Server seems to be working, NodeBB won't start anymore @yariplus @phit

**Comment by Electromaster232** [comment]
![screen shot 2017-09-30 at 9 30 52 pm](https://user-images.githubusercontent.com/25728719/31050877-aad63b6a-a626-11e7-9992-2bdfc71794be.png)
Also this when it goes to start

**Comment by Electromaster232** [comment]
Updating node to 1.6
That should hopefully help

**Comment by yariplus** [comment]
@phit Ahh you're right, I never pushed that change.

**Comment by yariplus** [comment]
@Electromaster232 That could actually make things worse XD

but let me know, and I will fix the errors.

**Comment by Electromaster232** [comment]
Wellll, its working now, but the plugin now has no effect or anything. No menu option, nothin. Lol
![screen shot 2017-09-30 at 10 26 40 pm](https://user-images.githubusercontent.com/25728719/31051139-7bbd437a-a62e-11e7-8457-a0bf454db33d.png)
![screen shot 2017-09-30 at 10 26 30 pm](https://user-images.githubusercontent.com/25728719/31051140-7bbfe68e-a62e-11e7-9786-4b09f1caf752.png)

@yariplus

**Comment by yariplus** [comment]
Give me a few minutes.

**Comment by Electromaster232** [comment]
Ok

**Comment by yariplus** [comment]
Apologizes, I will publish a patch tomorrow, my dev version is in a sorry state.

**Comment by Electromaster232** [comment]
That's no problem, I'm going to bed right now anyway.

**Comment by Electromaster232** [comment]
@yariplus Any luck?

**Comment by yariplus** [comment]
Doh, got called into work today. I'll be starting on it in a few minutes.

**Comment by Electromaster232** [comment]
oh lel sry to be annoyin ;)

**Comment by yariplus** [comment]
Not annoying at all. :) The plugin is just a bit outdated.

I'm about half done. I should have it ready by tomorrow.

**Comment by Electromaster232** [comment]
Cewl @yariplus . Saw a few commits today :smile: . Should I look on NodeBB for an update to the plugin?

**Comment by yariplus** [comment]
Not yet, but soon.

**Comment by yariplus** [comment]
Try alpha.13, let me know the results. Server config page and the server status widget should be working.

**Comment by Electromaster232** [comment]
Updated to newest (alpha.13). Still no menu options under the plugins tab. @yariplus

**Comment by Electromaster232** [comment]
3/10 07:58:37 [32399] - [33mwarn[39m: [plugins] Unable to parse library for: nodebb-plugin-minecraft-integration
3/10 07:58:37 [32399] - [31merror[39m: Error: Cannot find module 'templates.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at Object.<anonymous> (/home/ubuntu/nodebb/node_modules/nodebb-plugin-custom-widgets/library.js:17:28)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.Plugins.requireLibrary (/home/ubuntu/nodebb/src/plugins.js:44:32)
    at registerHooks (/home/ubuntu/nodebb/src/plugins/load.js:180:13)
    at /home/ubuntu/nodebb/src/plugins/load.js:138:6
    at /home/ubuntu/nodebb/node_modules/async/dist/async.js:3853:24
    at eachOfArrayLike (/home/ubuntu/nodebb/node_modules/async/dist/async.js:1003:9)

**Comment by yariplus** [comment]
Derp. Okay try 14

**Comment by Electromaster232** [comment]
Works!!! @yariplus
MC Server is still showing that error 


[Tue, 3. Oct 2017 15:23:00 EDT INFO] [NodeBB-Integration] Error connecting to the forum.
[Tue, 3. Oct 2017 15:23:00 EDT INFO] [NodeBB-Integration] io.socket.engineio.client.EngineIOException: xhr poll error

**Comment by yariplus** [comment]
Have you set origins in your conig.json to *:*



On Oct 3, 2017 3:23 PM, "Electromaster232" <notifications@github.com> wrote:

Works!!! @yariplus <https://github.com/yariplus>
MC Server is still showing that error

[Tue, 3. Oct 2017 15:23:00 EDT INFO] [NodeBB-Integration] Error connecting
to the forum.
[Tue, 3. Oct 2017 15:23:00 EDT INFO] [NodeBB-Integration]
io.socket.engineio.client.EngineIOException: xhr poll error

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/yariplus/nodebb-plugin-minecraft-integration/issues/107#issuecomment-333950778>,
or mute the thread

**Comment by Electromaster232** [comment]
@yariplus K, works, some stuff (top player list) and such crashes node, but I assume thats cause your not done. Also, the /register takes you to a "not found" page.

**Comment by yariplus** [comment]
Awesome! Yes that is correct, only the status widget is working at the
moment.

**Comment by yariplus** [comment]
If you want, you can open issues for specific features and I will
prioritize those.

**Comment by Electromaster232** [comment]
@yariplus Sweet, I'll def do that. Just wanted to say, thanks so much for your help, you could have easilly just ignored this or something else, but instead you _almost did a complete rewrite_ cause some guy came and said the plugin wasn't working. Thank you SO MUCH. Feel free to close this issue once you have read this message, and I'll be makin some new issues with the features that I think should be prioritised.
